modLoader="javafml"
loaderVersion="[4,)"
license="MPL-2.0"

[[mods]]
modId="turtlematic_testmod"
version="1.0"
displayName="Turtlematic Testmod"
description="Turtlematic server GameTests."

[[dependencies.turtlematic_testmod]]
modId="turtlematic"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.turtlematic_testmod]]
modId="testiarium"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
