kotlin.code.style = official
org.gradle.jvmargs = -Xmx4G
org.gradle.warning.mode = all
org.gradle.daemon=false
minecraftVersion=1.21.1
# Mod Properties
modVersion = 1.4.10
projectGroup = site.siredvin
mavenGroup = site.siredvin
modBaseName = turtlematic
# Curseforge
CURSEFORGE_RELEASE_TYPE=release
CURSEFORGE_ID=618288
MODRINTH_ID=UogK5QqE
MODRINTH_RELEASE_TYPE=release
