modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/SirEdvin/Turtlematic/issues"

[[mods]]
modId="turtlematic"
version="${file.jarVersion}"
displayName="Turtlematic"
displayURL="https://github.com/SirEdvin/Turtlematic/"
logoFile="pack.png"
authors="SirEdvin"
description='''
CC:T addon, that makes turtles great again!
'''

[[dependencies.turtlematic]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="computercraft"
type="required"
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="tweakium"
type="required"
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="broccolium"
type="required"
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="peripheralium"
type="required"
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"
