[versions]
# Base libraries
kotlin = "2.0.0"
kotlin-coroutines = "1.6.4"
kotlin-atomicfu = "0.20.2"
# Gradle plugins
sponge = "0.2.1-SNAPSHOT"
loom = "1.12.+"
# Core mod dependencies
cc-tweaked = "1.116.1"
broccolium = "1.4.6"
tweakium = "1.4.6"
peripheralium = "1.4.6"
broccolium-jjar = "[1.4.6, 1.5.0)"
tweakium-jjar = "[1.4.6, 1.5.0)"
peripheralium-jjar = "[1.4.6, 1.5.0)"
mixin = "0.8.5"
# Fabric dependencies
fabric-api = "0.116.3+1.21.1"
fabric-loader = "0.16.14"
fabric-kotlin = "1.11.0+kotlin.2.0.0"
forgeconfigapirt = "21.1.6"
modmenu = "11.0.1"
# NeoForge dependencies
neoforge = "21.1.9"
forge-kotlin = "5.7.0"
parchment = "2024.11.17"
parchmentMc = "1.21.1"
# Testing
testiarium = "0.1.1"
# Dev mod dependenceis
jei = "19.27.0.340"
rei = "16.0.799"

[libraries]
# Base libraries
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu-jvm", version.ref = "kotlin-atomicfu" }

# Core mod dependencies
cc-tweaked-common = {module = "cc.tweaked:cc-tweaked-1.21.1-common", version.ref = "cc-tweaked"}
cc-tweaked-common-api = {module = "cc.tweaked:cc-tweaked-1.21.1-common-api", version.ref = "cc-tweaked"}
cc-tweaked-core = {module = "cc.tweaked:cc-tweaked-1.21.1-core", version.ref = "cc-tweaked"}
common-config = {module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapirt"}
broccolium-core = {module = "site.siredvin:broccolium-common-1.21.1", version.ref = "broccolium"}
tweakium-core = {module = "site.siredvin:tweakium-common-1.21.1", version.ref = "tweakium"}
peripheralium-core = {module = "site.siredvin:peripheralium-common-1.21.1", version.ref = "peripheralium"}
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }

# Fabric mod dependencies
fabric-loader = {module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}
fabric-api = {module = "net.fabricmc.fabric-api:fabric-api", version.ref="fabric-api"}
fabric-kotlin = {module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin"}
fabric-config = {module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forgeconfigapirt"}
cc-tweaked-fabric-api = {module = "cc.tweaked:cc-tweaked-1.21.1-fabric-api", version.ref = "cc-tweaked"}
cc-tweaked-fabric = {module = "cc.tweaked:cc-tweaked-1.21.1-fabric", version.ref = "cc-tweaked"}
broccolium-fabric = {module = "site.siredvin:broccolium-fabric-1.21.1", version.ref = "broccolium"}
tweakium-fabric = {module = "site.siredvin:tweakium-fabric-1.21.1", version.ref = "tweakium"}
peripheralium-fabric = {module = "site.siredvin:peripheralium-fabric-1.21.1", version.ref = "peripheralium"}
modmenu = {module = "com.terraformersmc:modmenu", version.ref="modmenu"}

# Forge mod dependencies
cc-tweaked-forge =  {module = "cc.tweaked:cc-tweaked-1.21.1-forge", version.ref="cc-tweaked"}
forge-kotlin = {module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "forge-kotlin"}
broccolium-forge = {module = "site.siredvin:broccolium-forge-1.21.1", version.ref = "broccolium"}
tweakium-forge = {module = "site.siredvin:tweakium-forge-1.21.1", version.ref = "tweakium"}
peripheralium-forge = {module = "site.siredvin:peripheralium-forge-1.21.1", version.ref = "peripheralium"}
broccolium-jjar-forge = {module = "site.siredvin:broccolium-forge-1.21.1", version.ref = "broccolium-jjar"}
tweakium-jjar-forge = {module = "site.siredvin:tweakium-forge-1.21.1", version.ref = "tweakium-jjar"}
peripheralium-jjar-forge = {module = "site.siredvin:peripheralium-forge-1.21.1", version.ref = "peripheralium-jjar"}

# Testing
testiarium-core = { module = "site.siredvin:testiarium-core-1.21.1", version.ref = "testiarium" }
testiarium-forge = { module = "site.siredvin:testiarium-forge-1.21.1", version.ref = "testiarium" }
testiarium-fabric = { module = "site.siredvin:testiarium-fabric-1.21.1", version.ref = "testiarium" }

# Dev mod dependencies
jei-fabric = { module = "mezz.jei:jei-1.21.1-fabric", version.ref = "jei" }
jei-forge = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
rei-fabric = {module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei"}

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
vanillaGradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "sponge"}
loom = {id = "fabric-loom", version.ref = "loom"}

[bundles]
kotlin = ["kotlin-stdlib", "kotlin-coroutines", "kotlin-atomicfu"]
cccommon = ["cc-tweaked-common", "cc-tweaked-common-api", "cc-tweaked-core", "peripheralium-core", "tweakium-core", "broccolium-core"]
apicommon = ["common-config"]
fabric-cc = ["cc-tweaked-fabric", "cc-tweaked-core", "modmenu"]
fabric-include = ["broccolium-fabric", "tweakium-fabric", "peripheralium-fabric"]
fabric-core = ["fabric-api", "fabric-kotlin", "fabric-config", "fabric-loader"]
forge-raw = ["forge-kotlin"]
forge-cc = ["cc-tweaked-forge"]
forge-include = ["broccolium-forge", "tweakium-forge", "peripheralium-forge"]
forge-jjar = ["broccolium-jjar-forge", "tweakium-jjar-forge", "peripheralium-jjar-forge"]

# Minecraft
externalMods-forge-runtime = [
     "jei-forge",
]
externalMods-fabric-runtime = [
     "rei-fabric",
]

# Integration dependencies
externalMods-fabric-integrations-api = []

externalMods-fabric-integrations-full = [
]
externalMods-fabric-integrations-active = [
]
externalMods-fabric-integrations-activedep = [
]

externalMods-forge-integrations-full = [
]
externalMods-forge-integrations-active = [
]
externalMods-forge-integrations-activedep = [
]
