local automata = assert(peripheral.find("automata"), "Automata core is missing")
local config = automata.getConfiguration()
assert(config.interactionRadius == 2 and config.maxRadius == 2, "Expected tier-one radii")

local block = automata.look("block")
assert(block.name == "minecraft:chest", "Expected to look at chest")
assert(automata.setFuelConsumptionRate(1), "Expected fuel rate reset")
assert(automata.getFuelConsumptionRate() == 1, "Expected minimum fuel rate")
assert(automata.getCooldown("use") == 0, "Expected no initial use cooldown")
local ok, err = automata.setFuelConsumptionRate(0)
assert(ok == nil and err == "Too small fuel consumption rate", "Expected lower fuel-rate boundary")
ok, err = automata.setFuelConsumptionRate(3)
assert(ok == nil and err == "Too big fuel consumption rate", "Expected upper fuel-rate boundary")
assert(automata.setFuelConsumptionRate(2), "Expected maximum tier-one fuel rate")
local fuel = automata.getFuelLevel()
assert(automata.use("block"), "Expected to use chest")
assert(automata.getFuelLevel() == fuel - 2, "Expected doubled fuel consumption")
local cooldown = automata.getCooldown("use")
assert(cooldown > 0 and cooldown <= 500, "Expected fuel-reduced use cooldown")
ok, err = automata.use("block")
assert(ok == nil and err == "use is on cooldown", "Expected repeated operation cooldown")

local items = automata.scan("item", 2)
assert(#items == 1 and items[1].name == "minecraft:apple" and items[1].count == 3, "Expected to scan apples")
assert(automata.suck(2, "minecraft:apple"), "Expected to suck two apples")
assert(turtle.getItemCount(1) == 2, "Expected two apples in turtle inventory")

turtle.select(2)
assert(automata.swing("block"), "Expected to break chest")
